[SETUP] Initial project deploy
daw@vagrant:~/Desktop/prueba/bazaary$ #lanzo la comprobacion de requerimientos
daw@vagrant:~/Desktop/prueba/bazaary$ php app/check.php
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0

Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
  /etc/php5/cli/php.ini

> Checking Symfony requirements:
  ..................W........................

 [OK]
 Your system is ready to run Symfony projects

Optional recommendations to improve your setup
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 * xdebug.max_nesting_level should be above 100 in php.ini
   > Set "xdebug.max_nesting_level" to e.g. "250" in php.ini* to stop
   > Xdebug's infinite recursion protection erroneously throwing a
   > fatal error in your project.

Note  The command console could use a different php.ini file
~~~~  than the one used with your web server. To be on the
      safe side, please check the requirements from your web
      server using the web/config.php script.

daw@vagrant:~/Desktop/prueba/bazaary$ #lanzo la comprobacion de requerimientos, pero ahora redirecciono la informacion de lo que me saldrá en la pantalla hacia un fichero nuevo usando el caracter > que es hacia donde irá
daw@vagrant:~/Desktop/prueba/bazaary$ php app/check.php > fichero.txt
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
daw@vagrant:~/Desktop/prueba/bazaary$ php app/check.php > fichero.rpt
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
daw@vagrant:~/Desktop/prueba/bazaary$ git status
On branch jtapia
Your branch is up-to-date with 'origin/jtapia'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Commit_Symfony
	modified:   README.md
	deleted:    hechoConUnPush.txt
	deleted:    prueba.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitignore
	LICENSE
	UPGRADE-2.2.md
	UPGRADE-2.3.md
	UPGRADE-2.4.md
	UPGRADE.md
	app/
	composer.json
	composer.lock
	docs/uml/grupo3.mdj
	fichero.rpt
	fichero.txt
	src/
	web/

no changes added to commit (use "git add" and/or "git commit -a")
daw@vagrant:~/Desktop/prueba/bazaary$ git branch
  jonytapia
* jtapia
  master
daw@vagrant:~/Desktop/prueba/bazaary$ git checktout jonytapia
git: 'checktout' is not a git command. See 'git --help'.

Did you mean this?
	checkout
daw@vagrant:~/Desktop/prueba/bazaary$
daw@vagrant:~/Desktop/prueba/bazaary$ git checktout -jonytapia
git: 'checktout' is not a git command. See 'git --help'.

Did you mean this?
	checkout
daw@vagrant:~/Desktop/prueba/bazaary$ git checkout -jonytapia
error: unknown switch `j'
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...

    -q, --quiet           suppress progress reporting
    -b <branch>           create and checkout a new branch
    -B <branch>           create/reset and checkout a branch
    -l                    create reflog for new branch
    --detach              detach the HEAD at named commit
    -t, --track           set upstream info for new branch
    --orphan <new-branch>
                          new unparented branch
    -2, --ours            checkout our version for unmerged files
    -3, --theirs          checkout their version for unmerged files
    -f, --force           force checkout (throw away local modifications)
    -m, --merge           perform a 3-way merge with the new branch
    --overwrite-ignore    update ignored files (default)
    --conflict <style>    conflict style (merge or diff3)
    -p, --patch           select hunks interactively
    --ignore-skip-worktree-bits
                          do not limit pathspecs to sparse entries only
    --ignore-other-worktrees
                          do not check if another worktree is holding the given ref
    --progress            force progress reporting
    --recurse-submodules[=<checkout>]
                          control recursive updating of submodules

daw@vagrant:~/Desktop/prueba/bazaary$ git checkout jonytapia
error: Your local changes to the following files would be overwritten by checkout:
	README.md
Please, commit your changes or stash them before you can switch branches.
Aborting
daw@vagrant:~/Desktop/prueba/bazaary$ git branch
  jonytapia
* jtapia
  master
daw@vagrant:~/Desktop/prueba/bazaary$ git checkout -b jonytapia
fatal: A branch named 'jonytapia' already exists.
daw@vagrant:~/Desktop/prueba/bazaary$ git branch
  jonytapia
* jtapia
  master
daw@vagrant:~/Desktop/prueba/bazaary$ git checkout master
M	README.md
D	hechoConUnPush.txt
D	prueba.txt
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
daw@vagrant:~/Desktop/prueba/bazaary$ git branch
  jonytapia
  jtapia
* master
daw@vagrant:~/Desktop/prueba/bazaary$ git checkout jtapia
M	README.md
D	hechoConUnPush.txt
D	prueba.txt
Switched to branch 'jtapia'
Your branch is up-to-date with 'origin/jtapia'.
daw@vagrant:~/Desktop/prueba/bazaary$ git status
On branch jtapia
Your branch is up-to-date with 'origin/jtapia'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md
	deleted:    hechoConUnPush.txt
	deleted:    prueba.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitignore
	LICENSE
	UPGRADE-2.2.md
	UPGRADE-2.3.md
	UPGRADE-2.4.md
	UPGRADE.md
	app/
	composer.json
	composer.lock
	docs/uml/grupo3.mdj
	fichero.rpt
	fichero.txt
	src/
	web/

no changes added to commit (use "git add" and/or "git commit -a")
daw@vagrant:~/Desktop/prueba/bazaary$ git add -a
error: unknown switch `a'
usage: git add [<options>] [--] <pathspec>...

    -n, --dry-run         dry run
    -v, --verbose         be verbose

    -i, --interactive     interactive picking
    -p, --patch           select hunks interactively
    -e, --edit            edit current diff and apply
    -f, --force           allow adding otherwise ignored files
    -u, --update          update tracked files
    -N, --intent-to-add   record only the fact that the path will be added later
    -A, --all             add changes from all tracked and untracked files
    --ignore-removal      ignore paths removed in the working tree (same as --no-all)
    --refresh             don't add, only refresh the index
    --ignore-errors       just skip files which cannot be added because of errors
    --ignore-missing      check if - even missing - files are ignored in dry run

daw@vagrant:~/Desktop/prueba/bazaary$ git status
On branch jtapia
Your branch is up-to-date with 'origin/jtapia'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md
	deleted:    hechoConUnPush.txt
	deleted:    prueba.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitignore
	LICENSE
	UPGRADE-2.2.md
	UPGRADE-2.3.md
	UPGRADE-2.4.md
	UPGRADE.md
	app/
	composer.json
	composer.lock
	docs/uml/grupo3.mdj
	fichero.rpt
	fichero.txt
	src/
	web/

no changes added to commit (use "git add" and/or "git commit -a")
daw@vagrant:~/Desktop/prueba/bazaary$ git commit
On branch jtapia
Your branch is up-to-date with 'origin/jtapia'.
Changes not staged for commit:
	modified:   README.md
	deleted:    hechoConUnPush.txt
	deleted:    prueba.txt

Untracked files:
	.gitignore
	LICENSE
	UPGRADE-2.2.md
	UPGRADE-2.3.md
	UPGRADE-2.4.md
	UPGRADE.md
	app/
	composer.json
	composer.lock
	docs/uml/grupo3.mdj
	fichero.rpt
	fichero.txt
	src/
	web/

no changes added to commit
daw@vagrant:~/Desktop/prueba/bazaary$ git commit -a

Error reading /home/daw/.nano_history: Permission denied

Press Enter to continue starting nano.

Aborting commit due to empty commit message.
daw@vagrant:~/Desktop/prueba/bazaary$ git add
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
daw@vagrant:~/Desktop/prueba/bazaary$
daw@vagrant:~/Desktop/prueba/bazaary$ git add .
daw@vagrant:~/Desktop/prueba/bazaary$ git add .*
fatal: ..: '..' is outside repository
daw@vagrant:~/Desktop/prueba/bazaary$ git status
On branch jtapia
Your branch is up-to-date with 'origin/jtapia'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitignore
	new file:   LICENSE
	modified:   README.md
	new file:   UPGRADE-2.2.md
	new file:   UPGRADE-2.3.md
	new file:   UPGRADE-2.4.md
	new file:   UPGRADE.md
	new file:   app/.htaccess
	new file:   app/AppCache.php
	new file:   app/AppKernel.php
	new file:   app/Resources/views/base.html.twig
	new file:   app/Resources/views/default/index.html.twig
	new file:   app/SymfonyRequirements.php
	new file:   app/autoload.php
	renamed:    prueba.txt -> app/cache/.gitkeep
	new file:   app/check.php
	new file:   app/config/config.yml
	new file:   app/config/config_dev.yml
	new file:   app/config/config_prod.yml
	new file:   app/config/config_test.yml
	new file:   app/config/parameters.yml.dist
	new file:   app/config/routing.yml
	new file:   app/config/routing_dev.yml
	new file:   app/config/security.yml
	new file:   app/config/services.yml
	new file:   app/console
	renamed:    hechoConUnPush.txt -> app/logs/.gitkeep
	new file:   app/phpunit.xml.dist
	new file:   composer.json
	new file:   composer.lock
	new file:   docs/uml/grupo3.mdj
	new file:   fichero.rpt
	new file:   fichero.txt
	new file:   src/.htaccess
	new file:   src/AppBundle/AppBundle.php
	new file:   src/AppBundle/Controller/DefaultController.php
	new file:   src/AppBundle/Tests/Controller/DefaultControllerTest.php
	new file:   web/.htaccess
	new file:   web/app.php
	new file:   web/app_dev.php
	new file:   web/apple-touch-icon.png
	new file:   web/config.php
	new file:   web/favicon.ico
	new file:   web/robots.txt

daw@vagrant:~/Desktop/prueba/bazaary$ git reset -- LICENSE
daw@vagrant:~/Desktop/prueba/bazaary$ git config --global
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup

daw@vagrant:~/Desktop/prueba/bazaary$ git config--global
git: 'config--global' is not a git command. See 'git --help'.
daw@vagrant:~/Desktop/prueba/bazaary$ git config --global
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup

daw@vagrant:~/Desktop/prueba/bazaary$ git config <global>
bash: syntax error near unexpected token `newline'
daw@vagrant:~/Desktop/prueba/bazaary$ git config [<global>]
bash: global: No such file or directory
daw@vagrant:~/Desktop/prueba/bazaary$ git config --[<global>]
bash: global: No such file or directory
daw@vagrant:~/Desktop/prueba/bazaary$ git config --<global>
bash: syntax error near unexpected token `newline'
daw@vagrant:~/Desktop/prueba/bazaary$ git config --list
user.name=Jony Tapia
user.email=jonytapia.stucom@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
remote.origin.url=https://github.com/IFCD0210/bazaary.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
gui.wmstate=normal
gui.geometry=887x427+26+26 171 192
branch.jtapia.remote=origin
branch.jtapia.merge=refs/heads/jtapia
user.name=jtapia
daw@vagrant:~/Desktop/prueba/bazaary$ #con esto veo si tengo cuenta añadida al ggit
daw@vagrant:~/Desktop/prueba/bazaary$ git config --list
user.name=Jony Tapia
user.email=jonytapia.stucom@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
remote.origin.url=https://github.com/IFCD0210/bazaary.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
gui.wmstate=normal
gui.geometry=887x427+26+26 171 192
branch.jtapia.remote=origin
branch.jtapia.merge=refs/heads/jtapia
user.name=jtapia
daw@vagrant:~/Desktop/prueba/bazaary$ #verifico siempre en la rama que me encuentro antes de hacer algun commit
daw@vagrant:~/Desktop/prueba/bazaary$ git branch
  jonytapia
* jtapia
  master
daw@vagrant:~/Desktop/prueba/bazaary$ #ahora nos identificamos
daw@vagrant:~/Desktop/prueba/bazaary$ #perdon ahora hacemos el commit
daw@vagrant:~/Desktop/prueba/bazaary$